# Use an OpenJDK image with Java 21
FROM openjdk:21-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application JAR file into the container
COPY target/springboot-app-prodwell-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application runs on
EXPOSE 8080

# Set environment variables from the .env file
ENV SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
ENV SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
