# Use an OpenJDK image with Java 21
FROM openjdk:21-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application JAR file into the container
COPY target/springboot-app-prodwell-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application runs on
EXPOSE 8080

# Set environment variables from the .env file
ENV SPRING_DATA_MONGODB_URI="mongodb+srv://kartikchindarkar01:muaraK6k5jM8so36@sjsu.zgadi.mongodb.net/?retryWrites=true&w=majority&appName=sjsu"
ENV SPRING_DATA_MONGODB_DATABASE="prodwellDB"

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
