version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATA_MONGODB_URI=mongodb+srv://kartikchindarkar01:muaraK6k5jM8so36@sjsu.zgadi.mongodb.net/?retryWrites=true&w=majority&appName=sjsu
        - SPRING_DATA_MONGODB_DATABASE=prodwellDB